---
- hosts: localhost
  connection: local
  tasks:
    - debug:
        msg: "HELLO WORLD!"
    - name: execute some commands
      shell: |
        pwd; whoami; hostname
  post_tasks:
    - debug:
        msg: "end of execution"
        
